export const LEVELS = {
    1: {
        digit: 1,
        columns: 3,
        rows: 2,
        count: 6,
        animate: false,
    },
    2: {
        digit: 2,
        columns: 3,
        rows: 2,
        count: 6,
        animate: false,
    },
    3: {
        digit: 3,
        columns: 3,
        rows: 2,
        count: 6,
        animate: true,
    },
    4: {
        digit: 3,
        columns: 4,
        rows: 3,
        count: 12,
        animate: true,
    },
    5: {
        digit: 3,
        columns: 4,
        rows: 3,
        count: 12,
        animate: true,
    },
    6: {
        digit: 3,
        columns: 4,
        rows: 4,
        count: 16,
        animate: true,
    },
    7: {
        digit: 4,
        columns: 4,
        rows: 4,
        count: 16,
        animate: true,
    },
    8: {
        digit: 4,
        columns: 5,
        rows: 5,
        count: 25,
        animate: true,
    },
    9: {
        digit: 4,
        columns: 5,
        rows: 5,
        count: 25,
        animate: true,
    },
};